services:
  - type: web
    name: inovarena-api
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm ci
    startCommand: npm run start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVICE_ACCOUNT_KEY
        sync: false
      - key: LICENSE_PRIVATE_KEY
        sync: false
      - key: LICENSE_SECRET
        sync: false
